### ISSUE TITLE
Chat from DCS allies to Discord issue

### ISSUE THREAD

**Issue by agrondahl** [Special-K-s-Flightsim-Bots/DCSServerBot#1]
When a player seated in an aircraft in DCS chats to "allies", it is not reflected in Discord. 

Example:
![image](https://user-images.githubusercontent.com/83029764/117072050-325e2c00-ad30-11eb-94ea-c4c1097746b0.png)

All lines, except 3rd ("hi from allies) was sent to all. Those were all seen in discord, except "hi from allies":

![image](https://user-images.githubusercontent.com/83029764/117072195-5faada00-ad30-11eb-8b3b-866682c61162.png)

**Comment by karel26** [comment]
Messages for allies only don't work with the callback, so the system would have to be changed completely.
I would leave it like that for now, as private / allied-only messages are not meant to be put in the - public - discord. So messages from red to red would be seen by everybody, even blue.

**Comment by karel26** [comment]
Closed for now.
