### ISSUE TITLE
Not an "issue", more a question

### ISSUE THREAD

**Issue by DJ45X** [Special-K-s-Flightsim-Bots/DCSServerBot#12]
In reference to the DCS Desanitization, does the OS module need to be desanitized? I work for Fox3 Managed Solutions and out of abundance for security, we prefer not to desanitize the OS module. Would love to know if it's necessary or a work around is possible!

**Comment by karel26** [comment]
Hey mate, that is only needed for Moose atm, AIRBOSS uses os.time() in their luas atm, so not my requirement. I can perfectly live without it. I'm in contact with Franky already about their new way of sending data via UDP (we agreed on a format that we both can work with) and I'm quite sure we can get rid of it in a bit.
