### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Fallcrim** [Special-K-s-Flightsim-Bots/DCSServerBot#13]
Hi, this is not a problem with the programm but I'm interested in how you did this. Could you describe to me how you get the player stats from the server or the general information. 

Thanks and kind regards

**Comment by karel26** [comment]
I don't get the stats directly but what I get are events for anything happening in a mission like takeoffs, landings, kills, etc. There are basically two ways of doing that, one is with a Hook, using the DCS callbacks and the 2nd one is with an event listener inside of missions. I do both, depending on the level of stats people wanna gather.

**Comment by Fallcrim** [comment]
Thanks for the quick response. I only want the kills and deaths to start of. Could you exactly tell me how it works or refer to a piece of code that shows it?

Kind regards

**Comment by karel26** [comment]
You might imagine that I can't take the time to explain the whole code, you can just use the bot ;).
But you might want to have a look at the API documentation in your installation below the API directory. And there at a callback "onGameEvent".
In my code all that happens in the userstats plugin, in the listener.py

**Comment by Fallcrim** [comment]
Thanks for the reference to the API. Hope I can find how to make it work in my code. 
Btw without questioning the your bots quality, I want to use this stuff for a different project that doesn't deal with discord or other bots.

Kind regards

**Comment by Fallcrim** [comment]
Hi again, sorry for asking that much but how does the onGameEvent method get triggered in `plugins/userstats/listener.py`?

**Comment by karel26** [comment]
You need to write a Hook and place it in Scripts\Hooks. With that you get access to the respective API.

If you don't want to invent the wheel again and don't want any bot solution, take a look at perun.

**Comment by Fallcrim** [comment]
Could you send me a link for perun?

**Comment by karel26** [comment]
Mate, I do that as an exception. You can't expect me to google for you. So here you are:
https://github.com/szporwolik/perun

**Comment by Fallcrim** [comment]
I really appreciate your help. Thanks for your your time helping me out and with this comment I am done with asking you more stupid questions. 

Again thanks a lot and _kind regards_
