### ISSUE TITLE
Server not detected after startup

### ISSUE THREAD

**Issue by dividebysandwich** [Special-K-s-Flightsim-Bots/DCSServerBot#25]
Hi, I have a weird problem, our dcs server is starting fine, and in scripts/net/dcsserverbot/dcsserverbotconfig.lua I see the following:

```
-- DCSServerBotConfig.lua
----------------------------------------------------------
-- This file has been generated by DCSServerBot based on
-- the dcsserverbot.ini file located in the config sub-
-- directory of the DCSServerBot installation.
----------------------------------------------------------
-- !!! PLEASE DON'T CHANGE THIS FILE DIRECTLY BUT      !!!
-- !!! CHANGE THE ACCORDING VALUES IN dcsserverbot.ini !!!
----------------------------------------------------------
module('DCSServerBotConfig')

VERSION = '2.6.7'
-- General Values
BOT_HOST = '127.0.0.1'
BOT_PORT = 10042
CHAT_COMMAND_PREFIX = '-'
SERVER_USER = 'Admin'
-- Instance Values
DCS_HOST = '127.0.0.1'
DCS_PORT = 6666
STATISTICS = true           -- true = enable user statistics
MISSION_STATISTICS = true -- true = enable mission statistics
COALITIONS = false           -- true = enable coalitions
CHAT_CHANNEL = '1065304278194999356'   -- In-game chat will be replicated here
STATUS_CHANNEL = '1065304318690983956'   -- a persistent server and players status will be presented here
ADMIN_CHANNEL = '1065304424873992222'   -- admin commands can be fired here
MESSAGE_PLAYER_USERNAME = 'Your player name contains invalid characters. Please change your name to join our server.'
MESSAGE_PLAYER_DEFAULT_USERNAME = 'Please change your default player name at the top right of the multiplayer selection list to an individual one!'
MESSAGE_BAN = 'You are banned from this server. Reason: {}'
MESSAGE_SLOT_SPAMMING = 'You have been kicked for slot spamming!'

```

However DCSServerBot never finds out that the server started successfully, even though it did. When I restart DCSServerBot while DCS is running, I get the following:

```
2023-06-27 21:05:21.173 INFO    - Registering Discord Commands (this might take a bit) ...
2023-06-27 21:05:21.376 INFO    - Discord Commands registered.
2023-06-27 21:05:21.391 INFO    - Searching for running DCS servers (this might take a bit) ...
2023-06-27 21:05:24.407 INFO    - No running servers found.
2023-06-27 21:05:24.407 INFO    DCSServerBot started, accepting commands.

```

in dcsserverbot.ini I have this:

```
[DCS.openbeta_server]
DCS_HOST = 127.0.0.1
DCS_PORT = 6666
DCS_HOME = c:\\Users\\User\\Saved Games\\DCS.openbeta_server
STATISTICS = true
MISSION_STATISTICS = true

```

There's no error messages in dcs.log

Any ideas what I could try? I also tried a different port for DCS_PORT, like 16666, but no joy.

**Comment by spanner-uk** [comment]
I also have this issue.

Bot has been running fine for many months and through updates (so long as MissionScripting.lua is managed properly). 

I suspect the latest DCS update might have messed things up somehow. Perhaps changed the nature of the comms on port 6666. Not sure. I also updated the DCS Server bot to latest version so perhaps there is a bug there.

I will try some older DCS Server Bot releases and will report back if I make any progress toward getting it working.

**Comment by karel26** [comment]
Sorry guys, haven't seen that. Would you mind join my discord and discuss it over there, it's easier for me to keep track. Thanks!

**Comment by karel26** [comment]
And the bot is working fine on 244 servers rn. Must be something else.
https://discord.gg/AxFxZRJQj9

**Comment by dividebysandwich** [comment]
Thanks a lot to @karel26 for debugging this - For me the issue was twofold:
1) I was running Python 3.9 and I upgraded to Python 3.11.4 (the latest one)
2) I was running "python run.py" instead of run.cmd. Using run.cmd with the latest python fixed it for me. 

Afterwards, I had to start DCS via the bot once and then it was recognized immediately.

**Comment by spanner-uk** [comment]
In my case, couldn't see any specific errors but a clean re-install of the DCSServerBot sorted me out so suspect I messed something up doing a manual update of the bot.
