### ISSUE TITLE
Single DCS Instance

### ISSUE THREAD

**Issue by ICS-Vortex** [Special-K-s-Flightsim-Bots/DCSServerBot#26]
Is it possible to use only one DCS World Server instance and have multiple servers running only one installation and different SavedGames folders ?
When I starting configure multiple servers dcsserverbot.ini file - bot responds 
```
DCSServerBot
БОТ
 — Сегодня, в 11:56
@DCS Admin Can't reach server "ICS Vortex Test" for more than 3 minutes. Creating minidump and killing ...
Latest dcs-<timestamp>.log can be pulled with .download
If the scheduler is configured for this server, it will relaunch it automatically.
```
and kills running DCS instance. 

![image](https://github.com/Special-K-s-Flightsim-Bots/DCSServerBot/assets/13809571/fc65a15d-8051-4429-b6fe-fa4cf88f11e3)

**Comment by karel26** [comment]
That usually happens, if you have a port conflict. DCSServerBot should warn you about the most common ones already in your log file.
Besides that, LotAtc is a good candidate.
So double check all ports. If unsure, join my discord and send me the dcs.log files of both servers.

**Comment by ICS-Vortex** [comment]
Thanks. I will check logs and ports. I have no any 3rd Party plugins or mods installed. Clean DCS Server (modular) installation.

**Comment by ICS-Vortex** [comment]
I reconfigured both servers to be on different ports and so on. 
But now I am getting another issue. 
When I try to `.startup` server  - I get error:
![image](https://github.com/Special-K-s-Flightsim-Bots/DCSServerBot/assets/13809571/2794fc5a-4fc6-4923-8308-d03056a5e7bb)

**Comment by ICS-Vortex** [comment]
Logs from DCS instances.
[1dcs.zip](https://github.com/Special-K-s-Flightsim-Bots/DCSServerBot/files/12379429/1dcs.zip)
[2dcs.zip](https://github.com/Special-K-s-Flightsim-Bots/DCSServerBot/files/12379435/2dcs.zip)

**Comment by karel26** [comment]
Would you mind join my discord that would make it much easier for me and many more people are there to help

**Comment by karel26** [comment]
I see the DCSServerBot lua loaded in one of the servers. That means, the 2nd one isn't loading them, most likely due to a config issue.

**Comment by ICS-Vortex** [comment]
> Would you mind join my discord that would make it much easier for me and many more people are there to help

Yes, sure. Can you provide me a link ?
