### ISSUE TITLE
Music service/plugin not working

### ISSUE THREAD

**Issue by sevenfifty777** [Special-K-s-Flightsim-Bots/DCSServerBot#31]
Hello 
i got the following error
 ERROR	'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\DCSServerBot\core\listener.py", line 127, in processEvent
    await self.__events__[name](self, server, data)
  File "C:\DCSServerBot\core\listener.py", line 36, in __call__
    await self.callback(listener, server, data)
  File "C:\DCSServerBot\plugins\music\listener.py", line 15, in registerDCSServer
    await self.service.init_radios(server=server)
  File "C:\DCSServerBot\services\music\service.py", line 66, in init_radios
    radio: Radio = getattr(sys.modules['services.music.radios'], config['type'])(name=name, server=server)
                                                                 ~~~~~~^^^^^^^^

i found small issue with music plugin plugins\music\listener.py 
it seems that it needs to add some space for all lines containing  server=server  to server = server

**Comment by karel26** [comment]
No, that's a valid Python syntax and even the language recommendation to do so.
It is underlined, because that's where your issue happened. Can you send your config\service\music.yaml please?

Best would be to join my discord. Then I can have a look at your configuration. Something is off.

**Comment by sevenfifty777** [comment]
i have reviewed my config\service\music.yaml 
it seems it was  indentation issue , not sure why but when comparing with yaml in sample  , i got same spacing but it was highlighted in my file , i have recreated my file and it is working fine , i have reverted my change in listener
all works fine ( i may not use notepad++ to edit yaml files)

btw i try your discord link from https://special-k-s-flightsim-bots.github.io/DCSServerBot/, but link is invalid for me

Thx for your support

**Comment by karel26** [comment]
Try this one:
https://discord.gg/h2zGDH9szZ
