### ISSUE TITLE
Problem with install

### ISSUE THREAD

**Issue by Dmgerr** [Special-K-s-Flightsim-Bots/DCSServerBot#33]
Hey! Im stuck in install. I ave installed python 3.11 32bit, postgresql, git. When i try to run install.cmd from bot folder i get this:
Traceback (most recent call last):
  File "C:\Users\serwer\DCSServerBot\install.py", line 5, in <module>
    import psycopg
ModuleNotFoundError: No module named 'psycopg'
Please press any key to continue...

iI have already installed psycopg with pip command
C:\Users\serwer>pip install psycopg
Collecting psycopg
  Downloading psycopg-3.1.17-py3-none-any.whl (178 kB)
     ---------------------------------------- 178.0/178.0 kB 2.7 MB/s eta 0:00:00
Collecting typing-extensions>=4.1
  Downloading typing_extensions-4.9.0-py3-none-any.whl (32 kB)
Collecting tzdata
  Downloading tzdata-2023.4-py2.py3-none-any.whl (346 kB)
     ---------------------------------------- 346.6/346.6 kB 5.4 MB/s eta 0:00:00
Installing collected packages: tzdata, typing-extensions, psycopg
Successfully installed psycopg-3.1.17 typing-extensions-4.9.0 tzdata-2023.4

but problem persist.
Any ideas what im doing wrong?

**Comment by sevenfifty777** [comment]
as module python psycopg is missing , 
from your folder C:\Users\serwer\DCSServerBot  
you may try pip install -r requirements.txt 
if it is still failing , you may try : %USERPROFILE%\.dcssb\Scripts\pip install -r requirements.txt
and then %USERPROFILE%\.dcssb\Scripts\pip list | findstr psycopg to verify that the module is in dcssb libs
i recommend you to check the discord , you will find help with people having already same kind of error (https://discord.gg/mubxhmq2 )

**Comment by Dmgerr** [comment]
> as module python psycopg is missing , from your folder C:\Users\serwer\DCSServerBot you may try pip install -r requirements.txt if it is still failing , you may try : %USERPROFILE%.dcssb\Scripts\pip install -r requirements.txt and then %USERPROFILE%.dcssb\Scripts\pip list | findstr psycopg to verify that the module is in dcssb libs i recommend you to check the discord , you will find help with people having already same kind of error (https://discord.gg/mubxhmq2 )

$ pip list | findstr psycopg
psycopg           3.1.17

folder dcssb and dcssb\scripts

but still the same error with psycopg
