### ISSUE TITLE
Temporary incompatibility with Python3 V13

### ISSUE THREAD

**Issue by Vinggui** [Special-K-s-Flightsim-Bots/DCSServerBot#37]
It seems like Python v13 is not compatible yet with this package, because of psycopg2.
https://github.com/psycopg/psycopg2/issues/1628

I just installed it with Python v12 and it worked!

**Comment by karel26** [comment]
Python 3.13 is out since some days only and lots of 3rd party libs don't work with it yet. I'm not using psycopg2 btw but 3.
It took nearly a year for 3.12 to have all the libs working with it, expect something similar for 3.13. The bot code itself should work, but it's not tested.

**Comment by karel26** [comment]
I made it clear in the installation instructions now.
